import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import type { StepDef } from "../types";
import { fileMatches, messagesMerge, readJsonFile } from "./helpers";

/**
 * Steps 9-14: application identity slice (metadata, design, typography,
 * icons, branding, languages). Generic starter content only, no business copy.
 */

const HexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/, "hex color like #1d4ed8");

export const metadataStep: StepDef = {
  id: "app-metadata",
  title: "Application metadata",
  schema: z.object({
    appName: z.string().min(1).max(60),
    tagline: z.string().min(1).max(140),
    defaultLocale: z.enum(["en", "al"]).default("en"),
    baseUrl: z.string().url().optional(),
  }),
  ui: {
    title: "Application metadata",
    description: "Name, tagline, default language, and canonical base URL.",
    fields: [
      { name: "appName", label: "Application name", type: "text" },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "defaultLocale", label: "Default locale", type: "select", options: ["en", "al"] },
      { name: "baseUrl", label: "Canonical base URL", type: "text" },
    ],
  },
  docs: "Records the application's public identity. Downstream steps (languages, SEO, branding) read these values from setup state instead of asking again. Never stores secrets.",
  detect: (targetDir, values) => {
    const ok = fileMatches(
      targetDir,
      "shared/app-meta/generated.ts",
      metaContent(values["appName"] as string, values["tagline"] as string, values["defaultLocale"] as string),
    );
    return ok
      ? { status: "current", detail: "metadata matches" }
      : { status: "missing", detail: "metadata missing or stale" };
  },
  generate: (ctx) => [
    {
      path: "shared/app-meta/generated.ts",
      content: metaContent(
        ctx.values["appName"] as string,
        ctx.values["tagline"] as string,
        ctx.values["defaultLocale"] as string,
      ),
      owned: "generated",
    },
  ],
};

function metaContent(appName: string, tagline: string, defaultLocale: string): string {
  return `// GENERATED by setup (app-metadata). Do not hand edit.
export const APP_META = {
  appName: ${JSON.stringify(appName)},
  tagline: ${JSON.stringify(tagline)},
  defaultLocale: ${JSON.stringify(defaultLocale)},
} as const;
`;
}

export const designStep: StepDef = {
  id: "design",
  title: "Design",
  schema: z.object({
    primaryColor: HexColor,
    radius: z.enum(["0.5", "0.625", "0.75", "1.0"]).default("0.75"),
    darkMode: z.boolean().default(true),
  }),
  ui: {
    title: "Design tokens",
    description: "Primary color, corner radius, and dark mode support.",
    fields: [
      { name: "primaryColor", label: "Primary color (hex)", type: "text" },
      { name: "radius", label: "Corner radius (rem)", type: "select", options: ["0.5", "0.625", "0.75", "1.0"] },
      { name: "darkMode", label: "Dark mode", type: "boolean" },
    ],
  },
  docs: "Writes the design token section of the generated stylesheet as OKLCH-friendly CSS variables. Typography owns its own section of the same file; sections merge by marker so reruns preserve each other.",
  detect: (targetDir, values) =>
    sectionMatches(targetDir, "shared/themes/generated-tokens.css", "design", designBody(values))
      ? { status: "current", detail: "design tokens match" }
      : { status: "missing", detail: "design tokens missing or stale" },
  generate: (ctx) => [
    {
      path: "shared/themes/generated-tokens.css",
      content: applySection(ctx.targetDir, "shared/themes/generated-tokens.css", "design", designBody(ctx.values)),
      owned: "generated",
    },
  ],
};

function designBody(values: Record<string, unknown>): string {
  const radius = values["radius"] as string;
  return `:root {
  --primary: ${values["primaryColor"]};
  --radius: ${radius}rem;
}
.dark {
  --primary: ${values["primaryColor"]};
}`;
}

export const typographyStep: StepDef = {
  id: "typography",
  title: "Typography",
  schema: z.object({
    fontFamily: z.string().min(1).default("Geist"),
    monoFamily: z.string().min(1).default("Geist Mono"),
    baseSize: z.number().min(12).max(20).default(16),
  }),
  ui: {
    title: "Typography",
    description: "Font families and base size. Applied as CSS variables.",
    fields: [
      { name: "fontFamily", label: "Sans font", type: "text" },
      { name: "monoFamily", label: "Mono font", type: "text" },
      { name: "baseSize", label: "Base size (px)", type: "number" },
    ],
  },
  docs: "Writes the typography section of the generated stylesheet. Merges by marker into the same file the design step owns, so neither step clobbers the other.",
  detect: (targetDir, values) =>
    sectionMatches(targetDir, "shared/themes/generated-tokens.css", "typography", typographyBody(values))
      ? { status: "current", detail: "typography matches" }
      : { status: "missing", detail: "typography missing or stale" },
  generate: (ctx) => [
    {
      path: "shared/themes/generated-tokens.css",
      content: applySection(ctx.targetDir, "shared/themes/generated-tokens.css", "typography", typographyBody(ctx.values)),
      owned: "generated",
    },
  ],
};

function typographyBody(values: Record<string, unknown>): string {
  return `:root {
  --font-sans: ${values["fontFamily"]}, system-ui, sans-serif;
  --font-mono: ${values["monoFamily"]}, monospace;
  --font-size-base: ${values["baseSize"]}px;
}`;
}

function sectionBlock(marker: string, body: string): string {
  return `/* setup:${marker} -- managed, do not hand edit */\n${body}\n/* setup:end-${marker} */`;
}

/** Replace (or append) a marked section inside a CSS file. Other sections survive. */
export function applySection(targetDir: string, relPath: string, marker: string, body: string): string {
  const absolute = join(targetDir, relPath);
  const current = existsSync(absolute) ? readFileSync(absolute, "utf8") : "";
  const pattern = new RegExp(`/\\* setup:${marker}[\\s\\S]*?/\\* setup:end-${marker} \\*/`, "m");
  const block = sectionBlock(marker, body);
  if (pattern.test(current)) return current.replace(pattern, () => block);
  const separator = current === "" || current.endsWith("\n") ? "" : "\n";
  return `${current}${separator}\n${block}\n`;
}

function sectionMatches(targetDir: string, relPath: string, marker: string, body: string): boolean {
  const absolute = join(targetDir, relPath);
  if (!existsSync(absolute)) return false;
  return readFileSync(absolute, "utf8").includes(sectionBlock(marker, body));
}

export const iconsStep: StepDef = {
  id: "icons",
  title: "Icons",
  schema: z.object({
    set: z.enum(["lucide"]).default("lucide"),
    defaultSize: z.number().int().min(12).max(32).default(16),
    strokeWidth: z.number().min(1).max(3).default(2),
  }),
  ui: {
    title: "Icon system",
    description: "One icon set for the whole app, with default size and stroke.",
    fields: [
      { name: "set", label: "Icon set", type: "select", options: ["lucide"] },
      { name: "defaultSize", label: "Default size (px)", type: "number" },
      { name: "strokeWidth", label: "Stroke width", type: "number" },
    ],
  },
  docs: "Locks the single icon set and its defaults into a generated JSON config consumed by shared/icons wrappers. Only lucide is supported: mixing sets is a forbidden pattern.",
  detect: (targetDir, values) => {
    const current = readJsonFile(targetDir, "shared/icons/generated.json") as Record<string, unknown> | null;
    const ok =
      current?.["set"] === values["set"] &&
      current?.["defaultSize"] === values["defaultSize"] &&
      current?.["strokeWidth"] === values["strokeWidth"];
    return ok
      ? { status: "current", detail: "icon config matches" }
      : { status: "missing", detail: "icon config missing or stale" };
  },
  generate: (ctx) => [
    {
      path: "shared/icons/generated.json",
      content: `${JSON.stringify(
        { set: ctx.values["set"], defaultSize: ctx.values["defaultSize"], strokeWidth: ctx.values["strokeWidth"] },
        null,
        2,
      )}\n`,
      owned: "generated",
    },
  ],
};

export const brandingStep: StepDef = {
  id: "branding",
  title: "Branding",
  schema: z.object({
    brandName: z.string().min(1).max(40),
    brandColor: HexColor,
  }),
  ui: {
    title: "Branding",
    description: "Brand name and color used to render starter logo assets.",
    fields: [
      { name: "brandName", label: "Brand name", type: "text" },
      { name: "brandColor", label: "Brand color (hex)", type: "text" },
    ],
  },
  docs: "Renders starter SVG assets (logo plus social card) from the brand name and color. Placeholders, not final artwork: designers replace them without touching code.",
  detect: (targetDir, values) =>
    fileMatches(targetDir, "public/brand/logo.svg", logoSvg(values)) &&
    fileMatches(targetDir, "public/brand/og.svg", ogSvg(values))
      ? { status: "current", detail: "brand assets match" }
      : { status: "missing", detail: "brand assets missing or stale" },
  generate: (ctx) => [
    { path: "public/brand/logo.svg", content: logoSvg(ctx.values), owned: "generated" },
    { path: "public/brand/og.svg", content: ogSvg(ctx.values), owned: "generated" },
  ],
};

function initials(name: string): string {
  return name
    .split(/\s+/)
    .map((word) => word[0] ?? "")
    .join("")
    .slice(0, 2)
    .toUpperCase();
}

function logoSvg(values: Record<string, unknown>): string {
  const name = values["brandName"] as string;
  const color = values["brandColor"] as string;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="28" fill="${color}" />
  <text x="64" y="82" font-family="system-ui, sans-serif" font-size="56" font-weight="700" fill="#ffffff" text-anchor="middle">${initials(name)}</text>
</svg>
`;
}

function ogSvg(values: Record<string, unknown>): string {
  const name = values["brandName"] as string;
  const color = values["brandColor"] as string;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="${color}" />
  <text x="600" y="345" font-family="system-ui, sans-serif" font-size="96" font-weight="700" fill="#ffffff" text-anchor="middle">${name}</text>
</svg>
`;
}

const STARTER_KEYS: Record<string, Record<string, string>> = {
  en: {
    "app.tagline": "Starter tagline",
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Settings",
    "nav.admin": "Admin",
    "auth.signIn": "Sign in",
    "auth.signOut": "Sign out",
    "common.loading": "Loading",
  },
  al: {
    "app.tagline": "Moto fillestare",
    "nav.home": "Kreu",
    "nav.dashboard": "Paneli",
    "nav.settings": "Cilësimet",
    "nav.admin": "Admin",
    "auth.signIn": "Hyr",
    "auth.signOut": "Dil",
    "common.loading": "Po ngarkohet",
  },
};

export const languagesStep: StepDef = {
  id: "languages",
  title: "Languages",
  schema: z.object({
    locales: z.array(z.enum(["en", "al"])).min(1).default(["en", "al"]),
    primaryLocale: z.enum(["en", "al"]).default("en"),
  }),
  ui: {
    title: "Languages",
    description: "Enabled locales plus the primary one. Starter message files merge, never overwrite.",
    fields: [
      { name: "locales", label: "Enabled locales", type: "multiselect", options: ["en", "al"] },
      { name: "primaryLocale", label: "Primary locale", type: "select", options: ["en", "al"] },
    ],
  },
  docs: "Writes starter message files per enabled locale. Existing keys always win on merge, so reruns and custom copy survive. Keys stay flat and mirrored per the translations skill.",
  detect: (targetDir, values) => {
    const locales = values["locales"] as string[];
    const ok = locales.every((locale) => {
      const current = readJsonFile(targetDir, `messages/${locale}.json`) as Record<string, string> | null;
      if (!current) return false;
      return Object.keys(STARTER_KEYS[locale] ?? {}).every((key) => key in current);
    });
    return ok
      ? { status: "current", detail: "starter messages present" }
      : { status: "missing", detail: "starter messages missing or stale" };
  },
  generate: (ctx) => {
    const locales = ctx.values["locales"] as string[];
    const appName = (ctx.prior["app-metadata"]?.["appName"] as string | undefined) ?? "App";
    return locales.map((locale) =>
      messagesMerge(ctx.targetDir, locale, {
        "app.name": appName,
        ...(STARTER_KEYS[locale] ?? {}),
      }),
    );
  },
};
