import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { buildFirestoreRules, buildPermissionsDoc, buildStorageRules, resolveConfig } from "../../shared/permissions/generate";
import type { StepDef, WizardStateFile } from "../types";
import { fileMatches } from "./helpers";

/**
 * Steps 22-25: errors, SEO, review, and the final stamp. Review summarizes
 * prior state; generate compiles the authorization outputs and seals the run.
 */

export const errorsStep: StepDef = {
  id: "errors",
  title: "Errors",
  schema: z.object({
    prefix: z.string().regex(/^[A-Z]+$/, "uppercase prefix").default("APP"),
    codes: z.array(z.string().regex(/^[A-Z_]+$/, "SCREAMING_SNAKE")).min(1).default([
      "NOT_FOUND",
      "FORBIDDEN",
      "INVALID_INPUT",
      "CONFLICT",
      "UNAVAILABLE",
    ]),
  }),
  ui: {
    title: "Error catalog",
    description: "Machine readable error codes with a shared prefix.",
    fields: [
      { name: "prefix", label: "Code prefix", type: "text" },
      { name: "codes", label: "Codes (JSON array)", type: "text" },
    ],
  },
  docs: "Generates the typed error catalog features return from server actions and functions. Codes are stable identifiers; human messages stay in translations keyed by code.",
  detect: (targetDir, values) => {
    const ok = fileMatches(
      targetDir,
      "shared/errors/generated.ts",
      errorsContent(values["prefix"] as string, values["codes"] as string[]),
    );
    return ok
      ? { status: "current", detail: "error catalog matches" }
      : { status: "missing", detail: "error catalog missing or stale" };
  },
  generate: (ctx) => [
    {
      path: "shared/errors/generated.ts",
      content: errorsContent(ctx.values["prefix"] as string, ctx.values["codes"] as string[]),
      owned: "generated",
    },
  ],
};

function errorsContent(prefix: string, codes: string[]): string {
  const entries = codes.map((code) => `  ${code}: \`${prefix}_${code}\`,`).join("\n");
  return `// GENERATED by setup (errors). Do not hand edit.
export const ERROR_CODES = {
${entries}
} as const;
export type ErrorCode = keyof typeof ERROR_CODES;
`;
}

export const seoStep: StepDef = {
  id: "seo",
  title: "SEO",
  schema: z.object({
    baseUrl: z.string().url().optional(),
    defaultDescription: z.string().max(160).optional(),
  }),
  ui: {
    title: "SEO defaults",
    description: "Canonical base URL and fallback description. Name and tagline come from metadata.",
    fields: [
      { name: "baseUrl", label: "Canonical base URL", type: "text" },
      { name: "defaultDescription", label: "Fallback description", type: "text" },
    ],
  },
  docs: "Generates SEO defaults consumed by route metadata builders. Site name and tagline reuse the metadata step values from setup state; only locale independent settings are asked here.",
  detect: (targetDir, values, state) => {
    const meta = state?.values["app-metadata"] as { appName?: string; tagline?: string } | undefined;
    const ok = fileMatches(
      targetDir,
      "shared/seo/generated.ts",
      seoContent(
        (values["baseUrl"] as string | undefined) ?? "",
        (values["defaultDescription"] as string | undefined) ?? (meta?.tagline ?? ""),
        (meta?.appName ?? "App"),
      ),
    );
    return ok
      ? { status: "current", detail: "seo defaults match" }
      : { status: "missing", detail: "seo defaults missing or stale" };
  },
  generate: (ctx) => {
    const meta = ctx.prior["app-metadata"] as { appName?: string; tagline?: string } | undefined;
    return [
      {
        path: "shared/seo/generated.ts",
        content: seoContent(
          (ctx.values["baseUrl"] as string | undefined) ?? "",
          (ctx.values["defaultDescription"] as string | undefined) ?? (meta?.tagline ?? ""),
          (meta?.appName ?? "App"),
        ),
        owned: "generated",
      },
    ];
  },
};

function seoContent(baseUrl: string, description: string, siteName: string): string {
  return `// GENERATED by setup (seo). Do not hand edit.
export const SEO_DEFAULTS = {
  siteName: ${JSON.stringify(siteName)},
  defaultDescription: ${JSON.stringify(description)},
  baseUrl: ${JSON.stringify(baseUrl)},
} as const;
`;
}

function priorHash(state: WizardStateFile | null): string {
  return createHash("sha256")
    .update(JSON.stringify(state?.values ?? {}), "utf8")
    .digest("hex")
    .slice(0, 16);
}

export const reviewStep: StepDef = {
  id: "review",
  title: "Review",
  schema: z.object({}),
  ui: {
    title: "Review",
    description: "Read only summary of every prior step. No inputs.",
    fields: [],
  },
  docs: "Renders the human review document from setup state: completed steps plus their non secret values plus a content hash. Regenerates whenever prior values change, so review never describes a stale run.",
  detect: (targetDir, _values, state) => {
    const absolute = join(targetDir, "docs", "SETUP-REVIEW.md");
    if (!existsSync(absolute)) return { status: "missing", detail: "review document absent" };
    const ok = readFileSync(absolute, "utf8").includes(`<!-- values-hash: ${priorHash(state)} -->`);
    return ok
      ? { status: "current", detail: "review matches current values" }
      : { status: "stale", detail: "prior values changed since review" };
  },
  generate: (ctx) => [
    {
      path: "docs/SETUP-REVIEW.md",
      content: reviewContent(ctx.prior),
      owned: "generated",
    },
  ],
};

function reviewContent(prior: Record<string, Record<string, unknown>>): string {
  const hash = createHash("sha256").update(JSON.stringify(prior), "utf8").digest("hex").slice(0, 16);
  const rows = Object.entries(prior)
    .map(([step, values]) => `### ${step}\n\n\`\`\`json\n${JSON.stringify(values, null, 2)}\n\`\`\``)
    .join("\n\n");
  return `<!-- values-hash: ${hash} -->
<!-- GENERATED by setup (review). Do not hand edit. -->
# Setup review

Non secret values recorded by the wizard. Secrets never appear here.

${rows || "_No steps recorded yet._"}
`;
}

export const generateStep: StepDef = {
  id: "generate",
  title: "Generate",
  schema: z.object({
    confirm: z.literal(true),
  }),
  ui: {
    title: "Final stamp",
    description: "Compile rules and docs, then seal the run with a manifest. Confirm to proceed.",
    fields: [],
  },
  docs: "Compiles firestore.rules, storage.rules, and docs/PERMISSIONS.md from the authorization model (base config plus wizard overrides), then writes .setup-complete.json sealing the file hashes. Reruns recompile deterministically and skip byte identical files.",
  detect: (targetDir, _values, state) => {
    const absolute = join(targetDir, ".setup-complete.json");
    if (!existsSync(absolute)) return { status: "missing", detail: "no completion manifest" };
    try {
      const manifest = JSON.parse(readFileSync(absolute, "utf8")) as {
        steps?: string[];
        files?: Record<string, string>;
      };
      const expected = expectedManifest(targetDir, state);
      const ok =
        JSON.stringify(manifest.steps) === JSON.stringify(expected.steps) &&
        JSON.stringify(manifest.files) === JSON.stringify(expected.files) &&
        (state?.completedSteps.includes("review") ?? false);
      return ok
        ? { status: "current", detail: "manifest matches sealed state" }
        : { status: "stale", detail: "state changed since the stamp" };
    } catch {
      return { status: "stale", detail: "manifest unreadable" };
    }
  },
  generate: (ctx) => {
    const config = resolveConfig(ctx.targetDir);
    const built = {
      "firestore.rules": buildFirestoreRules(config),
      "storage.rules": buildStorageRules(config),
      "docs/PERMISSIONS.md": buildPermissionsDoc(config),
    };
    const manifest = {
      version: 1 as const,
      steps: [...new Set([...Object.keys(ctx.prior), "generate"])].sort(),
      files: manifestFiles(ctx.targetDir, ctx.hashes, built),
    };
    return [
      { path: "firestore.rules", content: built["firestore.rules"], owned: "generated" as const },
      { path: "storage.rules", content: built["storage.rules"], owned: "generated" as const },
      { path: "docs/PERMISSIONS.md", content: built["docs/PERMISSIONS.md"], owned: "generated" as const },
      {
        path: ".setup-complete.json",
        content: `${JSON.stringify(manifest, null, 2)}\n`,
        owned: "generated" as const,
      },
    ];
  },
};

function hashText(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

/** Expected manifest file map: prior hashes plus this stamp's own outputs. */
function manifestFiles(
  targetDir: string,
  hashes: Record<string, string>,
  built: Record<string, string>,
): Record<string, string> {
  void targetDir;
  const files: Record<string, string> = {};
  for (const [path, hash] of Object.entries(hashes)) {
    if (path !== ".setup-complete.json") files[path] = hash;
  }
  for (const [path, content] of Object.entries(built)) {
    files[path] = hashText(content);
  }
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => (a < b ? -1 : 1)));
}

function expectedManifest(
  targetDir: string,
  state: WizardStateFile | null,
): { steps: string[]; files: Record<string, string> } {
  const config = resolveConfig(targetDir);
  const built = {
    "firestore.rules": buildFirestoreRules(config),
    "storage.rules": buildStorageRules(config),
    "docs/PERMISSIONS.md": buildPermissionsDoc(config),
  };
  const steps = [...new Set([...Object.keys(state?.values ?? {}), "generate"])].sort();
  return {
    steps,
    files: manifestFiles(targetDir, state?.fileHashes ?? {}, built),
  };
}
