import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import type { StepDef } from "../types";
import {
  fileMatches,
  firebaseJsonMerge,
  gitignoreMerge,
  readJsonFile,
} from "./helpers";

/**
 * Steps 1-8: bootstrap plus the Firebase platform slice. Each step owns its
 * files: firebase.json sections merge, rules compile at the final stamp.
 */

const GITIGNORE_BLOCK = `# starter kit (managed by setup, safe to keep)
.firebase/
.firebaserc
*-key.json
*service-account*.json
serviceAccountKey.json
.env.local`;

export const bootstrapStep: StepDef = {
  id: "bootstrap",
  title: "Bootstrap",
  schema: z.object({
    appName: z.string().min(1).max(60),
    nodeMajor: z.number().int().min(20).default(22),
  }),
  ui: {
    title: "Bootstrap the project",
    description: "Name the app and confirm the runtime before anything is written.",
    fields: [
      { name: "appName", label: "Application name", type: "text" },
      { name: "nodeMajor", label: "Node major version", type: "number" },
    ],
  },
  docs: "Bootstrap names the application and guards the runtime floor. It writes the managed .gitignore block (secrets, Firebase cache, service account files) and nothing else. Rerunning never removes user entries: the block merges by marker.",
  detect: (targetDir) => {
    const file = gitignoreMerge(targetDir, GITIGNORE_BLOCK);
    return fileMatches(targetDir, ".gitignore", file.content)
      ? { status: "current", detail: "managed gitignore block present" }
      : { status: "missing", detail: "managed gitignore block absent" };
  },
  generate: (ctx) => [gitignoreMerge(ctx.targetDir, GITIGNORE_BLOCK)],
};

const ProjectIdSchema = z
  .string()
  .min(1)
  .max(40)
  .regex(/^[a-z0-9-]+$/, "lowercase letters, digits, and dashes only");

export const firebaseProjectStep: StepDef = {
  id: "firebase-project",
  title: "Firebase project",
  schema: z.object({
    projectId: ProjectIdSchema,
    region: z.string().min(1).default("europe-west1"),
  }),
  ui: {
    title: "Firebase project",
    description: "Bind the app to a Firebase project id and default region.",
    fields: [
      { name: "projectId", label: "Project ID", type: "text" },
      { name: "region", label: "Default region", type: "text" },
    ],
  },
  docs: "Binds the Firebase project id used by deploy targets and the default Functions region. Writes .firebaserc only; credentials never enter setup state.",
  detect: (targetDir, values) => {
    const current = readJsonFile(targetDir, ".firebaserc") as { projects?: { default?: string } } | null;
    return current?.projects?.default === (values["projectId"] as string)
      ? { status: "current", detail: "firebaserc project matches" }
      : { status: "missing", detail: "firebaserc project missing or stale" };
  },
  generate: (ctx) => [
    {
      path: ".firebaserc",
      content: `${JSON.stringify({ projects: { default: ctx.values["projectId"] } }, null, 2)}\n`,
      owned: "generated",
    },
  ],
};

export const firebaseAuthStep: StepDef = {
  id: "firebase-auth",
  title: "Firebase Authentication",
  schema: z.object({
    providers: z.array(z.enum(["email", "google"])).min(1).default(["email"]),
  }),
  ui: {
    title: "Sign in methods",
    description: "Enable the identity providers this app offers.",
    fields: [{ name: "providers", label: "Providers", type: "multiselect", options: ["email", "google"] }],
  },
  docs: "Selects the sign in methods. Generates the typed provider allowlist consumed by shared/auth. Adding a method is minor; removing one follows the breaking change workflow for signed in users.",
  detect: (targetDir, values) => {
    const providers = values["providers"] as string[];
    const ok =
      fileMatches(
        targetDir,
        "shared/auth/generated-config.ts",
        `// GENERATED by setup (firebase-auth). Do not hand edit.\nexport const ENABLED_AUTH_PROVIDERS = ${JSON.stringify(providers)} as const;\nexport type EnabledAuthProvider = (typeof ENABLED_AUTH_PROVIDERS)[number];\n`,
      );
    return ok
      ? { status: "current", detail: "provider allowlist matches" }
      : { status: "missing", detail: "provider allowlist missing or stale" };
  },
  generate: (ctx) => {
    const providers = ctx.values["providers"] as string[];
    return [
      {
        path: "shared/auth/generated-config.ts",
        content: `// GENERATED by setup (firebase-auth). Do not hand edit.\nexport const ENABLED_AUTH_PROVIDERS = ${JSON.stringify(providers)} as const;\nexport type EnabledAuthProvider = (typeof ENABLED_AUTH_PROVIDERS)[number];\n`,
        owned: "generated",
      },
    ];
  },
};

export const firebaseAdminStep: StepDef = {
  id: "firebase-admin",
  title: "Firebase Admin",
  schema: z
    .object({
      mode: z.enum(["emulator", "service-account"]),
      projectId: z.string().min(1).optional(),
      clientEmail: z.string().email().optional(),
      privateKey: z.string().min(1).optional(),
    })
    .refine(
      (value) =>
        value.mode === "emulator" ||
        (Boolean(value.projectId) && Boolean(value.clientEmail) && Boolean(value.privateKey)),
      { message: "service-account mode requires projectId, clientEmail, and privateKey" },
    ),
  ui: {
    title: "Admin credentials",
    description: "Emulators need nothing. Deploys need a service account, which is written straight to .env.local and never stored in setup state.",
    fields: [
      { name: "mode", label: "Credential mode", type: "select", options: ["emulator", "service-account"] },
      { name: "projectId", label: "Admin project ID", type: "text" },
      { name: "clientEmail", label: "Client email", type: "text" },
      { name: "privateKey", label: "Private key", type: "secret", secret: true },
    ],
  },
  docs: "Configures server privilege. Emulator mode needs no secrets. Service account mode merges the three credential vars into .env.local without touching existing keys, and the private key is flagged secret so it never lands in setup state or logs.",
  detect: (targetDir, values) => {
    if (values["mode"] === "emulator") {
      const firebase = readJsonFile(targetDir, "firebase.json") as { emulators?: unknown } | null;
      return firebase?.emulators
        ? { status: "current", detail: "emulator mode with emulator config present" }
        : { status: "missing", detail: "emulator config not yet generated" };
    }
    const local = parseEnvFile(targetDir);
    return local["FIREBASE_ADMIN_PROJECT_ID"]
      ? { status: "current", detail: "admin project id present in .env.local" }
      : { status: "missing", detail: "admin credentials not yet provided" };
  },
  generate: (ctx) => {
    if (ctx.values["mode"] === "emulator") return [];
    return [mergeLocalEnv(ctx.targetDir, ctx.values)];
  },
};

function parseEnvFile(targetDir: string): Record<string, string> {
  const absolute = join(targetDir, ".env.local");
  if (!existsSync(absolute)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(absolute, "utf8").split("\n")) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (match) out[match[1]] = match[2];
  }
  return out;
}

/** Merge credential vars into .env.local without overwriting existing keys. */
function mergeLocalEnv(targetDir: string, values: Record<string, unknown>): Extract<ReturnType<StepDef["generate"]>[number], { path: string }> {
  const current = parseEnvFile(targetDir);
  const wanted: Record<string, string> = {
    FIREBASE_ADMIN_PROJECT_ID: values["projectId"] as string,
    FIREBASE_ADMIN_CLIENT_EMAIL: values["clientEmail"] as string,
    FIREBASE_ADMIN_PRIVATE_KEY: values["privateKey"] as string,
  };
  const next = { ...wanted, ...current };
  const content = `${Object.entries(next)
    .map(([key, value]) => `${key}=${value}`)
    .join("\n")}\n`;
  return { path: ".env.local", content, owned: "generated" };
}

export const emulatorStep: StepDef = {
  id: "emulator",
  title: "Emulator",
  schema: z.object({
    authPort: z.number().int().min(1024).max(65535).default(9099),
    functionsPort: z.number().int().min(1024).max(65535).default(5001),
    firestorePort: z.number().int().min(1024).max(65535).default(8080),
    storagePort: z.number().int().min(1024).max(65535).default(9199),
    uiPort: z.number().int().min(1024).max(65535).default(4000),
    uiEnabled: z.boolean().default(true),
  }),
  ui: {
    title: "Emulator Suite",
    description: "Pin local ports for Auth, Functions, Firestore, Storage, and the UI.",
    fields: [
      { name: "authPort", label: "Auth port", type: "number" },
      { name: "functionsPort", label: "Functions port", type: "number" },
      { name: "firestorePort", label: "Firestore port", type: "number" },
      { name: "storagePort", label: "Storage port", type: "number" },
      { name: "uiPort", label: "UI port", type: "number" },
      { name: "uiEnabled", label: "Enable Emulator UI", type: "boolean" },
    ],
  },
  docs: "Pins the Emulator Suite ports into firebase.json so every developer and CI run boots the same topology. Auth, Firestore, Storage, and Functions emulators plus the UI are all required by the test gates.",
  detect: (targetDir, values) => {
    const firebase = readJsonFile(targetDir, "firebase.json") as { emulators?: Record<string, unknown> } | null;
    const expected = emulatorSection(values);
    return JSON.stringify(firebase?.emulators) === JSON.stringify(expected)
      ? { status: "current", detail: "emulator ports match" }
      : { status: "missing", detail: "emulator section missing or stale" };
  },
  generate: (ctx) => [firebaseJsonMerge(ctx.targetDir, "emulators", emulatorSection(ctx.values))],
};

function emulatorSection(values: Record<string, unknown>): Record<string, unknown> {
  return {
    auth: { port: values["authPort"] },
    functions: { port: values["functionsPort"] },
    firestore: { port: values["firestorePort"] },
    storage: { port: values["storagePort"] },
    ui: { enabled: values["uiEnabled"], port: values["uiPort"] },
    singleProjectMode: true,
  };
}

const INDEXES_STARTER = `{
  "indexes": [],
  "fieldOverrides": []
}
`;

export const firestoreStep: StepDef = {
  id: "firestore",
  title: "Firestore",
  schema: z.object({
    rulesFile: z.string().min(1).default("firestore.rules"),
    indexesFile: z.string().min(1).default("firestore.indexes.json"),
  }),
  ui: {
    title: "Firestore",
    description: "Point firebase.json at the rules and indexes files. Rules compile at the final stamp.",
    fields: [
      { name: "rulesFile", label: "Rules file", type: "text" },
      { name: "indexesFile", label: "Indexes file", type: "text" },
    ],
  },
  docs: "Wires the Firestore rules and indexes paths. The rules file itself compiles from the authorization model at the generate step, so this step only guarantees the pointer plus a valid starter indexes file (existing valid indexes are preserved).",
  detect: (targetDir, values) => {
    const firebase = readJsonFile(targetDir, "firebase.json") as { firestore?: unknown } | null;
    const indexes = readJsonFile(targetDir, values["indexesFile"] as string) as {
      indexes?: unknown;
    } | null;
    const ok =
      JSON.stringify(firebase?.firestore) ===
        JSON.stringify({ rules: values["rulesFile"], indexes: values["indexesFile"] }) &&
      Array.isArray(indexes?.indexes);
    return ok
      ? { status: "current", detail: "firestore wiring valid" }
      : { status: "missing", detail: "firestore wiring missing or stale" };
  },
  generate: (ctx) => {
    const files = [firebaseJsonMerge(ctx.targetDir, "firestore", {
      rules: ctx.values["rulesFile"],
      indexes: ctx.values["indexesFile"],
    })];
    const existing = readJsonFile(ctx.targetDir, ctx.values["indexesFile"] as string) as {
      indexes?: unknown;
    } | null;
    if (!Array.isArray(existing?.indexes)) {
      files.push({ path: ctx.values["indexesFile"] as string, content: INDEXES_STARTER, owned: "generated" });
    }
    return files;
  },
};

export const storageStep: StepDef = {
  id: "storage",
  title: "Storage",
  schema: z.object({
    rulesFile: z.string().min(1).default("storage.rules"),
  }),
  ui: {
    title: "Storage",
    description: "Point firebase.json at the rules file. Rules compile at the final stamp.",
    fields: [{ name: "rulesFile", label: "Rules file", type: "text" }],
  },
  docs: "Wires the Storage rules path. Rule content compiles from the authorization model at the generate step.",
  detect: (targetDir, values) => {
    const firebase = readJsonFile(targetDir, "firebase.json") as { storage?: unknown } | null;
    return JSON.stringify(firebase?.storage) === JSON.stringify({ rules: values["rulesFile"] })
      ? { status: "current", detail: "storage wiring matches" }
      : { status: "missing", detail: "storage wiring missing or stale" };
  },
  generate: (ctx) => [firebaseJsonMerge(ctx.targetDir, "storage", { rules: ctx.values["rulesFile"] })],
};

const FUNCTIONS_PACKAGE = (region: string) =>
  `{
  "name": "functions",
  "private": true,
  "version": "0.1.0",
  "engines": { "node": "22" },
  "main": "lib/index.js",
  "scripts": {
    "build": "tsc -p tsconfig.json"
  },
  "dependencies": {
    "firebase-admin": "14.4.0",
    "firebase-functions": "7.4.0",
    "zod": "4.6.5"
  },
  "devDependencies": {
    "typescript": "5.9.3"
  }
}
`;

const FUNCTIONS_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "rootDir": "src",
    "declaration": true,
    "sourceMap": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "lib"]
}
`;

const FUNCTIONS_INDEX = (region: string) =>
  `import { onCall, HttpsError } from "firebase-functions/v2/https";
import { initializeApp, getApps } from "firebase-admin/app";

if (getApps().length === 0) {
  initializeApp();
}

/** Authenticated liveness probe. Starter only, no business logic. */
export const ping = onCall({ region: "${region}" }, async (request) => {
  if (!request.auth) {
    throw new HttpsError("unauthenticated", "Sign in first.");
  }
  return { ok: true, uid: request.auth.uid, now: new Date().toISOString() };
});
`;

export const functionsStep: StepDef = {
  id: "functions",
  title: "Functions",
  schema: z.object({
    region: z.string().min(1).default("europe-west1"),
  }),
  ui: {
    title: "Cloud Functions",
    description: "Scaffold the 2nd generation functions package. Existing application code is never overwritten.",
    fields: [{ name: "region", label: "Functions region", type: "text" }],
  },
  docs: "Scaffolds functions/package.json, tsconfig.json, src/index.ts (an authenticated ping only), and the firebase.json functions section. Sources are application owned: the wizard writes them once and refuses silent overwrites afterwards.",
  detect: (targetDir) => {
    const firebase = readJsonFile(targetDir, "firebase.json") as { functions?: unknown } | null;
    return firebase?.functions && existsSync(join(targetDir, "functions/src/index.ts"))
      ? { status: "current", detail: "functions scaffold present" }
      : { status: "missing", detail: "functions scaffold missing" };
  },
  generate: (ctx) => [
    firebaseJsonMerge(ctx.targetDir, "functions", [
      { source: "functions", codebase: "default", predeploy: ["npm --prefix functions run build"] },
    ]),
    {
      path: "functions/package.json",
      content: FUNCTIONS_PACKAGE(ctx.values["region"] as string),
      owned: "application",
    },
    { path: "functions/tsconfig.json", content: FUNCTIONS_TSCONFIG, owned: "application" },
    {
      path: "functions/src/index.ts",
      content: FUNCTIONS_INDEX(ctx.values["region"] as string),
      owned: "application",
    },
  ],
};
